version: '3.3'

services:
  node_app:
    restart: unless-stopped
    build: .
    volumes:
      - ./:/home/node_app
    ports:
      - 9000:8000
  
  react_app:
    restart: unless-stopped
    build: ./frontend
    volumes:
      - ./frontend:/home/react_app
    ports:
      - 5000:3000

  redis:
    restart: unless-stopped
    image: redis
    ports:
      - 6379:6379
    volumes:
      - /redis-data:/data